import { useState } from 'react'
import {
  ArrowDownLeft, ArrowRight, ArrowUpRight, BadgeCheck, BarChart3, Bell, Check,
  ChevronDown, ChevronRight, CircleHelp, Clock3, Copy, CreditCard, Download,
  Eye, EyeOff, Fingerprint, Gift, Globe2, Headphones, Home, Layers3, LockKeyhole,
  LogOut, Menu, Moon, MoreHorizontal, PieChart, Plus, Search, Send, Settings,
  ShieldCheck, Sparkles, TrendingUp, Upload, UserRound, Users, WalletCards, X, Zap
} from 'lucide-react'
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart as RePieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

type Page = 'dashboard'|'portfolio'|'deposit'|'withdraw'|'transactions'|'affiliate'|'profile'
type AuthMode = 'login'|'signup'|'forgot'

const growth = [
  {m:'Jan', value:8000},{m:'Feb', value:8400},{m:'Mar', value:8100},{m:'Apr', value:9200},
  {m:'May', value:9600},{m:'Jun', value:9400},{m:'Jul', value:10600},{m:'Aug', value:11200},
  {m:'Sep', value:10900},{m:'Oct', value:11800},{m:'Nov', value:12100},{m:'Dec', value:12450},
]
const transactions = [
  {title:'Bank deposit', id:'DEP-839201', date:'Today, 09:42', amount:'+$2,000.00', status:'Confirmed', icon:'down'},
  {title:'Portfolio allocation', id:'INV-281940', date:'Aug 15, 14:20', amount:'−$1,500.00', status:'Completed', icon:'chart'},
  {title:'Recorded return', id:'RET-120438', date:'Aug 12, 11:05', amount:'+$284.12', status:'Completed', icon:'up'},
  {title:'Withdrawal', id:'WDR-582014', date:'Aug 08, 16:31', amount:'−$500.00', status:'Processing', icon:'send'},
]
const nav = [
  {id:'dashboard',label:'Overview',icon:Home},{id:'portfolio',label:'Portfolio',icon:PieChart},
  {id:'deposit',label:'Deposit',icon:ArrowDownLeft},{id:'withdraw',label:'Withdraw',icon:ArrowUpRight},
  {id:'transactions',label:'Transactions',icon:CreditCard},{id:'affiliate',label:'Affiliate',icon:Users},
] as const

function Logo({light=false}:{light?:boolean}){
  return <div className={'logo '+(light?'light':'')}><span className="logoMark"><i/><i/><i/></span><span>capitalia</span></div>
}
function Avatar(){return <div className="avatar">AK<span className="online"/></div>}
function Status({children}:{children:string}){return <span className={'status '+children.toLowerCase()}><i/>{children}</span>}

function Landing({onAuth}:{onAuth:(mode:AuthMode)=>void}){
  return <div className="landing">
    <nav className="publicNav wrap"><Logo light/><div className="publicLinks"><a href="#features">Why Capitalia</a><a href="#how">How it works</a><a href="#security">Security</a><a href="#help">Help</a></div><div className="navActions"><button className="textBtn" onClick={()=>onAuth('login')}>Log in</button><button className="btn btnLight" onClick={()=>onAuth('signup')}>Open an account <ArrowRight size={16}/></button></div><button className="mobileMenu" aria-label="Menu"><Menu/></button></nav>
    <main>
      <section className="hero wrap">
        <div className="heroCopy"><div className="eyebrow"><Sparkles size={14}/> A clearer way to manage your investments</div><h1>Grow your capital with a <em>smarter</em> investment experience.</h1><p>Manage your funds, monitor your portfolio, and access a modern investment experience from anywhere.</p><div className="heroActions"><button className="btn btnMint" onClick={()=>onAuth('signup')}>Get started <ArrowRight size={17}/></button><button className="btn btnGhost" onClick={()=>document.getElementById('features')?.scrollIntoView()}>Explore platform <ArrowDownLeft className="rotate" size={17}/></button></div><div className="heroProof"><div className="proofFaces"><span>JM</span><span>RL</span><span>SK</span></div><p><b>Designed for clarity</b><br/>Track authorized account data in one secure place</p></div></div>
        <div className="heroVisual" aria-label="Illustrative portfolio dashboard preview">
          <div className="orb one"/><div className="orb two"/><div className="previewCard">
            <div className="previewTop"><Logo/><span><Bell size={17}/><Avatar/></span></div><div className="previewWelcome"><small>Good morning, Alex</small><h3>Your portfolio</h3></div>
            <div className="previewBalance"><div><small>Total portfolio value</small><strong>$12,450.00</strong><span className="gain"><TrendingUp size={13}/> 8.2% this year</span></div><div className="miniChart"><svg viewBox="0 0 230 76"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#16a47a" stopOpacity=".27"/><stop offset="1" stopColor="#16a47a" stopOpacity="0"/></linearGradient></defs><path d="M0,65 C25,60 28,44 50,49 S80,53 94,36 S124,41 141,26 S171,31 185,17 S211,22 230,5 L230,76 L0,76Z" fill="url(#fill)"/><path d="M0,65 C25,60 28,44 50,49 S80,53 94,36 S124,41 141,26 S171,31 185,17 S211,22 230,5" fill="none" stroke="#16a47a" strokeWidth="3"/></svg></div></div>
            <div className="previewStats"><div><span className="roundIcon green"><ArrowDownLeft/></span><small>Deposited</small><b>$10,000</b></div><div><span className="roundIcon blue"><Layers3/></span><small>Invested</small><b>$9,800</b></div><div><span className="roundIcon gold"><TrendingUp/></span><small>Returns</small><b>$2,450</b></div></div>
            <div className="activityTitle"><b>Recent activity</b><span>View all</span></div><div className="miniActivity"><span className="roundIcon green"><ArrowDownLeft/></span><div><b>Bank deposit</b><small>Today, 9:42 AM</small></div><strong>+$2,000.00</strong></div>
          </div>
          <div className="floatBadge secure"><ShieldCheck/><span><b>Account protected</b><small>Security controls enabled</small></span></div><div className="floatBadge access"><Globe2/><span><b>24/7 access</b><small>Wherever you are</small></span></div>
        </div>
      </section>
      <section className="trust"><div className="wrap trustRow"><p>Built for confident account management</p>{[[ShieldCheck,'Secure accounts'],[Eye,'Transparent tracking'],[Zap,'Clear requests'],[BarChart3,'Professional dashboard'],[Globe2,'24/7 access']].map(([I,t]:any)=><div key={t}><I/>{t}</div>)}</div></section>
      <section className="features wrap" id="features"><div className="sectionIntro"><span>THE CAPITALIA EXPERIENCE</span><h2>Everything you need.<br/><em>Nothing you don't.</em></h2><p>A refined financial workspace designed to keep your account information clear, organized, and accessible.</p></div><div className="featureGrid">
        <article className="featureLarge"><div><span className="featureIcon"><BarChart3/></span><h3>Your financial picture, in focus</h3><p>See balances, recorded returns, deposits, and withdrawals in one thoughtfully designed dashboard.</p><a onClick={()=>onAuth('signup')}>Explore the dashboard <ArrowRight/></a></div><div className="focusVisual"><small>PORTFOLIO VALUE</small><strong>$12,450.00</strong><span>+$284.12 this month</span><div className="bars">{[35,48,42,58,52,66,72,68,84,91,86,100].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></div></article>
        <article><span className="featureIcon"><ShieldCheck/></span><h3>Security by design</h3><p>Multi-factor authentication, session controls, and transaction verification help protect every account.</p><div className="securityLine"><Fingerprint/><span><b>Two-factor authentication</b><small>Additional account protection</small></span><span className="toggle on"/></div></article>
        <article><span className="featureIcon"><Users/></span><h3>Grow your network</h3><p>Share your unique referral link and track qualification progress with complete transparency.</p><div className="referralMini"><div><span>QUALIFICATION PROGRESS</span><b>37 <small>/ 100 referrals</small></b></div><span className="progress"><i style={{width:'37%'}}/></span></div></article>
      </div></section>
      <section className="securitySection" id="security"><div className="wrap securityInner"><div><span className="overline">SECURITY & TRANSPARENCY</span><h2>Your account deserves<br/>serious protection.</h2><p>Capitalia is designed around responsible financial communication, strong access controls, and transparent records.</p><button className="btn btnLight" onClick={()=>onAuth('signup')}>Create your secure account <ArrowRight/></button></div><div className="securityPoints">{[[LockKeyhole,'Encrypted account data','Sensitive information is protected in transit and at rest.'],[Fingerprint,'Two-factor authentication','Add a second verification step to your login.'],[Eye,'Transparent records','View authorized account activity and transaction statuses.'],[Bell,'Real-time security alerts','Stay informed about important account activity.']].map(([I,t,d]:any)=><div key={t}><span><I/></span><div><b>{t}</b><p>{d}</p></div><Check/></div>)}</div></div></section>
    </main>
    <footer><div className="wrap"><Logo light/><p>Modern investment account management, built for clarity.</p><span>© 2026 Capitalia. Investing involves risk. Returns are not guaranteed.</span></div></footer>
  </div>
}

function Auth({mode:initial,onClose,onSuccess}:{mode:AuthMode,onClose:()=>void,onSuccess:()=>void}){
 const [mode,setMode]=useState(initial); const [show,setShow]=useState(false)
 return <div className="authPage"><div className="authBrand"><Logo light/><div><span className="overline">INVEST WITH CLARITY</span><h2>A more thoughtful way to manage your capital.</h2><p>Secure access, transparent records, and one elegant place for your entire investment account.</p></div><small>Investing involves risk. Returns are not guaranteed.</small></div><div className="authPanel"><button className="authClose" onClick={onClose}><X/></button><div className="authForm">
   <div className="mobileAuthLogo"><Logo/></div><span className="authShield"><ShieldCheck/></span><h1>{mode==='login'?'Welcome back':mode==='signup'?'Create your account':'Reset your password'}</h1><p>{mode==='login'?'Sign in to continue to your investment dashboard.':mode==='signup'?'Get started with a secure Capitalia account.':'Enter your email and we’ll send reset instructions.'}</p>
   {mode==='signup'&&<><label>Full name<input placeholder="Alex Morgan"/></label><div className="fieldRow"><label>Email address<input type="email" placeholder="alex@example.com"/></label><label>Phone number<input placeholder="+1 555 000 0000"/></label></div></>}
   {mode!=='signup'&&<label>Email address<input type="email" placeholder="name@example.com"/></label>}
   {mode!=='forgot'&&<label>Password<div className="password"><input type={show?'text':'password'} placeholder="Enter your password"/><button onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>}
   {mode==='signup'&&<><label>Confirm password<input type="password" placeholder="Confirm your password"/></label><label>Referral code <small>(optional)</small><input placeholder="Enter referral code"/></label></>}
   {mode==='login'&&<div className="formMeta"><label className="check"><input type="checkbox"/> Remember me</label><button onClick={()=>setMode('forgot')}>Forgot password?</button></div>}
   <button className="btn btnPrimary authSubmit" onClick={mode==='forgot'?()=>setMode('login'):onSuccess}>{mode==='login'?'Sign in securely':mode==='signup'?'Create secure account':'Send reset link'} <ArrowRight/></button>
   <div className="authSwitch">{mode==='login'?<>New to Capitalia? <button onClick={()=>setMode('signup')}>Create an account</button></>:mode==='signup'?<>Already have an account? <button onClick={()=>setMode('login')}>Sign in</button></>:<button onClick={()=>setMode('login')}>← Return to sign in</button>}</div><div className="secureNote"><LockKeyhole/> Protected by encrypted authentication</div>
 </div></div></div>
}

function Sidebar({page,setPage,collapsed,setCollapsed}:{page:Page,setPage:(p:Page)=>void,collapsed:boolean,setCollapsed:(v:boolean)=>void}){
 return <aside className={'sidebar '+(collapsed?'collapsed':'')}><div className="sideTop"><Logo light/><button onClick={()=>setCollapsed(!collapsed)}><ChevronRight/></button></div><div className="userMini"><Avatar/><span><b>Alex Kim</b><small>Verified investor <BadgeCheck/></small></span><MoreHorizontal/></div><small className="navLabel">MAIN MENU</small><nav>{nav.map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>setPage(n.id)}><n.icon/><span>{n.label}</span>{n.id==='affiliate'&&<i className="navNew">NEW</i>}</button>)}</nav><small className="navLabel">ACCOUNT</small><nav><button onClick={()=>setPage('profile')} className={page==='profile'?'active':''}><Settings/><span>Settings</span></button><button><CircleHelp/><span>Help & support</span></button></nav><div className="sideSecurity"><ShieldCheck/><span><b>Account protected</b><small>2FA is enabled</small></span><Check/></div><button className="logout"><LogOut/><span>Log out</span></button></aside>
}
function AppHeader({page,setPage}:{page:Page,setPage:(p:Page)=>void}){return <header className="appHeader"><div><h1>{page==='dashboard'?'Overview':page[0].toUpperCase()+page.slice(1)}</h1><p>{page==='dashboard'?'Tuesday, August 18, 2026':'Manage your account details and activity.'}</p></div><div className="headerActions"><button className="searchBtn"><Search/><span>Search</span><kbd>⌘ K</kbd></button><button className="iconBtn"><Moon/></button><button className="iconBtn bell"><Bell/><i>3</i></button><button className="headerProfile" onClick={()=>setPage('profile')}><Avatar/><span><b>Alex Kim</b><small>Investor</small></span><ChevronDown/></button></div></header>}
function MetricCard({label,value,change,icon:Icon,tone='green'}:{label:string,value:string,change:string,icon:any,tone?:string}){return <article className="metric"><div className={'metricIcon '+tone}><Icon/></div><div className="metricTop"><span>{label}</span><button><MoreHorizontal/></button></div><strong>{value}</strong><small className={change.includes('Pending')?'muted':'positive'}>{change.includes('Pending')?<Clock3/>:<TrendingUp/>}{change}</small></article>}

function Dashboard({setPage}:{setPage:(p:Page)=>void}){return <>
 <div className="welcomeRow"><div><h2>Welcome back, Alex <span>👋</span></h2><p>Here’s what’s happening with your investment account today.</p></div><div><button className="btn btnOutline" onClick={()=>setPage('withdraw')}><ArrowUpRight/> Withdraw</button><button className="btn btnPrimary" onClick={()=>setPage('deposit')}><Plus/> Add funds</button></div></div>
 <div className="metrics"><MetricCard label="Total balance" value="$12,450.00" change="8.2% this year" icon={WalletCards}/><MetricCard label="Available balance" value="$2,650.00" change="Ready to withdraw" icon={CreditCard} tone="blue"/><MetricCard label="Invested capital" value="$9,800.00" change="78.7% allocated" icon={Layers3} tone="purple"/><MetricCard label="Recorded returns" value="$2,450.00" change="+$284.12 this month" icon={TrendingUp} tone="gold"/><MetricCard label="Pending withdrawal" value="$500.00" change="Processing" icon={Clock3} tone="orange"/></div>
 <div className="dashGrid"><article className="panel chartPanel"><div className="panelHead"><div><h3>Portfolio performance</h3><p>Recorded account value over time</p></div><div className="range">{['7D','1M','3M','6M','1Y','ALL'].map(x=><button className={x==='1Y'?'active':''} key={x}>{x}</button>)}</div></div><div className="chartValue"><strong>$12,450.00</strong><span><TrendingUp/> 8.2%</span><small>Jan 1 – Aug 18, 2026</small></div><div className="mainChart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={growth} margin={{left:0,right:8,top:10,bottom:0}}><defs><linearGradient id="chartgreen" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#0aa678" stopOpacity=".22"/><stop offset="1" stopColor="#0aa678" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e9eeeb" strokeDasharray="4 4"/><XAxis dataKey="m" tickLine={false} axisLine={false} tick={{fontSize:11,fill:'#89958f'}}/><YAxis domain={[7000,13000]} tickFormatter={v=>'$'+v/1000+'k'} tickLine={false} axisLine={false} tick={{fontSize:11,fill:'#89958f'}}/><Tooltip formatter={(v:any)=>'$'+Number(v).toLocaleString()} contentStyle={{borderRadius:12,border:'1px solid #e2e9e5'}}/><Area type="monotone" dataKey="value" stroke="#07966d" strokeWidth={2.5} fill="url(#chartgreen)"/></AreaChart></ResponsiveContainer></div><p className="chartDisclaimer"><ShieldCheck/> Values shown are based on recorded account data. Past performance does not guarantee future results.</p></article>
 <article className="panel allocation"><div className="panelHead"><div><h3>Portfolio allocation</h3><p>Current capital distribution</p></div><button><MoreHorizontal/></button></div><div className="donut"><ResponsiveContainer width="100%" height="100%"><RePieChart><Pie data={[{v:62},{v:23},{v:15}]} dataKey="v" innerRadius={62} outerRadius={82} paddingAngle={3} startAngle={90} endAngle={-270}>{['#087556','#4d70c8','#e0ab4b'].map(c=><Cell key={c} fill={c}/>)}</Pie></RePieChart></ResponsiveContainer><div><strong>$9.8k</strong><small>Invested</small></div></div><div className="legend"><div><i className="g"/><span>Growth portfolio<small>Core allocation</small></span><b>62%</b></div><div><i className="b"/><span>Income portfolio<small>Income-focused</small></span><b>23%</b></div><div><i className="y"/><span>Cash reserve<small>Unallocated capital</small></span><b>15%</b></div></div><button className="fullLink" onClick={()=>setPage('portfolio')}>View portfolio details <ArrowRight/></button></article>
 </div>
 <div className="bottomGrid"><article className="panel recent"><div className="panelHead"><div><h3>Recent transactions</h3><p>Your latest account activity</p></div><button className="linkBtn" onClick={()=>setPage('transactions')}>View all <ArrowRight/></button></div>{transactions.map((t,i)=><div className="transaction" key={t.id}><span className={'txIcon '+t.icon}>{t.icon==='down'?<ArrowDownLeft/>:t.icon==='chart'?<BarChart3/>:t.icon==='up'?<TrendingUp/>:<Send/>}</span><div><b>{t.title}</b><small>{t.id}</small></div><span className="txDate">{t.date}</span><strong className={t.amount[0]==='+'?'credit':''}>{t.amount}</strong><Status>{t.status}</Status><ChevronRight/></div>)}</article><article className="panel quick"><div className="panelHead"><div><h3>Quick actions</h3><p>Common account tasks</p></div></div>{[[ArrowDownLeft,'Add funds','Make a new deposit','deposit'],[ArrowUpRight,'Request withdrawal','Transfer available funds','withdraw'],[Download,'Download statement','Get your monthly report','transactions'],[Headphones,'Contact support','We’re here to help','profile']].map(([I,t,d,p]:any)=><button key={t} onClick={()=>setPage(p)}><span><I/></span><div><b>{t}</b><small>{d}</small></div><ChevronRight/></button>)}</article></div>
 </>}

function Portfolio(){return <div className="pageContent"><div className="welcomeRow"><div><h2>Your portfolio</h2><p>A transparent view of your recorded investment activity.</p></div><button className="btn btnOutline"><Download/> Export statement</button></div><div className="metrics four"><MetricCard label="Total invested" value="$9,800.00" change="78.7% allocated" icon={Layers3}/><MetricCard label="Current value" value="$12,450.00" change="8.2% this year" icon={TrendingUp}/><MetricCard label="Total deposits" value="$10,500.00" change="4 confirmed" icon={ArrowDownLeft} tone="blue"/><MetricCard label="Total withdrawals" value="$500.00" change="1 processing" icon={ArrowUpRight} tone="orange"/></div><article className="panel chartPanel portfolioChart"><div className="panelHead"><div><h3>Balance history</h3><p>Based on backend-supplied account records</p></div><div className="range"><button>7D</button><button>1M</button><button>3M</button><button className="active">1Y</button><button>ALL</button></div></div><div className="mainChart"><ResponsiveContainer><AreaChart data={growth}><defs><linearGradient id="pg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#087556" stopOpacity=".2"/><stop offset="1" stopColor="#087556" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0ee"/><XAxis dataKey="m" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area dataKey="value" type="monotone" fill="url(#pg)" stroke="#087556" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></article></div>}
function Deposit(){const [sent,setSent]=useState(false); return <div className="pageContent narrowPage"><div className="welcomeRow"><div><h2>Add funds</h2><p>Select a method and submit your deposit information.</p></div></div>{sent?<div className="successCard"><span><Check/></span><h2>Deposit submitted</h2><p>Your deposit request is now being reviewed.</p><div><small>Reference ID</small><b>DEP-904821</b><small>Status</small><Status>Pending</Status></div><button className="btn btnPrimary" onClick={()=>setSent(false)}>Make another deposit</button></div>:<div className="formLayout"><article className="panel formCard"><div className="stepLabel"><span>1</span> Deposit details</div><label>Deposit method</label><div className="methodGrid"><button className="selected"><CreditCard/><b>Bank transfer</b><Check/></button><button><Globe2/><b>Wire transfer</b></button></div><label>Amount</label><div className="moneyInput"><span>$</span><input defaultValue="2,000.00"/><i>USD</i></div><small>Minimum deposit: $100.00</small><label>Payment reference</label><input placeholder="Enter bank or payment reference"/><label className="upload"><Upload/><b>Upload payment receipt</b><small>PDF, JPG or PNG · Max 10 MB</small></label><button className="btn btnPrimary full" onClick={()=>setSent(true)}>Submit deposit <ArrowRight/></button></article><aside className="panel instructions"><ShieldCheck/><h3>Payment instructions</h3><p>Transfer your chosen amount using the verified account details supplied after confirmation.</p><hr/><b>What happens next?</b><ol><li><span>1</span>Submit your deposit details</li><li><span>2</span>Our team verifies the payment</li><li><span>3</span>Your balance updates once confirmed</li></ol><div className="notice"><Clock3/> Deposits are never reflected until payment is verified.</div></aside></div>}</div>}
function Withdraw(){const [confirm,setConfirm]=useState(false);return <div className="pageContent narrowPage"><div className="welcomeRow"><div><h2>Withdraw funds</h2><p>Request a secure transfer from your available balance.</p></div></div><div className="balanceBanner"><div><small>AVAILABLE TO WITHDRAW</small><strong>$2,650.00</strong></div><ShieldCheck/><span><b>Protected request</b><small>2FA verification required</small></span></div><div className="formLayout"><article className="panel formCard"><label>Withdrawal method</label><select><option>Bank account •••• 2048</option></select><label>Withdrawal amount</label><div className="moneyInput"><span>$</span><input placeholder="0.00"/><i>USD</i></div><div className="amountPills"><button>$250</button><button>$500</button><button>$1,000</button><button>Max</button></div><label>Confirm password</label><input type="password" placeholder="Enter your account password"/><div className="notice"><Clock3/> Estimated processing: 1–3 business days</div><button className="btn btnPrimary full" onClick={()=>setConfirm(true)}>Review withdrawal <ArrowRight/></button></article><aside className="panel instructions"><h3>Request summary</h3><div className="summaryLine"><span>Available balance</span><b>$2,650.00</b></div><div className="summaryLine"><span>Minimum withdrawal</span><b>$100.00</b></div><div className="summaryLine"><span>Processing fee</span><b>$0.00</b></div><hr/><p className="fineprint">Withdrawal eligibility and minimums are supplied by platform configuration and may vary by account.</p></aside></div>{confirm&&<div className="modalBack"><div className="modal"><button onClick={()=>setConfirm(false)}><X/></button><span className="authShield"><ShieldCheck/></span><h2>Verify your request</h2><p>Enter the 6-digit code from your authenticator app to continue.</p><div className="otp">{[1,2,3,4,5,6].map(x=><input key={x} maxLength={1}/>)}</div><button className="btn btnPrimary full" onClick={()=>setConfirm(false)}>Confirm withdrawal</button></div></div>}</div>}
function Transactions(){return <div className="pageContent"><div className="welcomeRow"><div><h2>Transactions</h2><p>Search, filter, and review your complete account history.</p></div><button className="btn btnOutline"><Download/> Export CSV</button></div><div className="filterBar"><div><Search/><input placeholder="Search reference or transaction"/></div><select><option>All types</option></select><select><option>All statuses</option></select><button><Clock3/> Date range</button></div><article className="panel transactionTable"><div className="tableHead"><span>TRANSACTION</span><span>DATE</span><span>METHOD</span><span>AMOUNT</span><span>STATUS</span><span/></div>{transactions.concat([{title:'Affiliate commission',id:'AFF-308492',date:'Aug 02, 10:14',amount:'+$75.00',status:'Confirmed',icon:'up'}]).map(t=><div className="tableRow" key={t.id}><div><span className={'txIcon '+t.icon}>{t.icon==='down'?<ArrowDownLeft/>:t.icon==='chart'?<BarChart3/>:t.icon==='up'?<TrendingUp/>:<Send/>}</span><span><b>{t.title}</b><small>{t.id}</small></span></div><span>{t.date}</span><span>Account balance</span><strong className={t.amount.startsWith('+')?'credit':''}>{t.amount}</strong><Status>{t.status}</Status><MoreHorizontal/></div>)}</article></div>}
function Affiliate(){return <div className="pageContent"><div className="welcomeRow"><div><h2>Affiliate network</h2><p>Share Capitalia and track your qualification progress.</p></div></div><div className="referralHero"><div><span className="overline">YOUR UNIQUE REFERRAL LINK</span><h2>Build your network. Track every step.</h2><p>Earn commissions when referrals meet the platform’s configured qualification criteria.</p><div className="copyLink"><span>capitalia.app/register?ref=ALEXK</span><button><Copy/> Copy</button></div></div><Gift/></div><div className="metrics four"><MetricCard label="Total referrals" value="48" change="6 this month" icon={Users}/><MetricCard label="Qualified referrals" value="37" change="77% qualification rate" icon={BadgeCheck}/><MetricCard label="Total earnings" value="$1,275.00" change="+$150 this month" icon={TrendingUp} tone="gold"/><MetricCard label="Withdrawable" value="$825.00" change="Available now" icon={WalletCards} tone="blue"/></div><div className="affiliateGrid"><article className="panel qualification"><div className="panelHead"><div><h3>Affiliate qualification</h3><p>Progress toward withdrawal eligibility</p></div><Status>Active</Status></div><div className="qualNum"><strong>37</strong><span>/ 100<br/><small>qualified referrals</small></span></div><span className="bigProgress"><i style={{width:'37%'}}/></span><p><b>63 more qualified referrals</b> needed to unlock the current affiliate withdrawal requirement.</p><div className="configNote"><Settings/><span><b>Rules are platform-configured</b><small>Requirements, commissions, and schedules may be updated by administrators.</small></span></div></article><article className="panel network"><div className="panelHead"><div><h3>Your referral network</h3><p>Level 1 · Direct referrals</p></div><button className="linkBtn">View all <ArrowRight/></button></div>{[['MO','Maya O.','Qualified'],['JL','Jordan L.','Qualified'],['RS','Robin S.','Pending'],['TN','Taylor N.','Qualified']].map(x=><div key={x[1]}><span className="avatar small">{x[0]}</span><span><b>{x[1]}</b><small>Joined August 2026</small></span><Status>{x[2]}</Status></div>)}</article></div></div>}
function Profile(){return <div className="pageContent"><div className="welcomeRow"><div><h2>Account settings</h2><p>Manage your personal information, security, and preferences.</p></div></div><div className="settingsGrid"><aside className="panel settingsNav"><button className="active"><UserRound/> Personal information</button><button><ShieldCheck/> Security & 2FA</button><button><BadgeCheck/> Verification</button><button><Bell/> Notifications</button><button><Settings/> Preferences</button></aside><article className="panel profileForm"><div className="profileTop"><Avatar/><div><h3>Alex Kim</h3><p>alex.kim@example.com</p><Status>Verified</Status></div><button className="btn btnOutline">Change photo</button></div><hr/><h3>Personal information</h3><p>Keep your contact details accurate and up to date.</p><div className="fieldRow"><label>Full name<input defaultValue="Alex Kim"/></label><label>Email address<input defaultValue="alex.kim@example.com"/></label><label>Phone number<input defaultValue="+1 (555) 019-2048"/></label><label>Country<select><option>United States</option></select></label></div><button className="btn btnPrimary">Save changes</button><div className="securityBox"><ShieldCheck/><div><b>Two-factor authentication is enabled</b><p>Your account has an additional layer of sign-in protection.</p></div><button>Manage</button></div></article></div></div>}

function Platform({onLogout}:{onLogout:()=>void}){const [page,setPage]=useState<Page>('dashboard');const [collapsed,setCollapsed]=useState(false);return <div className="platform"><Sidebar page={page} setPage={setPage} collapsed={collapsed} setCollapsed={setCollapsed}/><div className="appShell"><AppHeader page={page} setPage={setPage}/><main className="appMain">{page==='dashboard'?<Dashboard setPage={setPage}/>:page==='portfolio'?<Portfolio/>:page==='deposit'?<Deposit/>:page==='withdraw'?<Withdraw/>:page==='transactions'?<Transactions/>:page==='affiliate'?<Affiliate/>:<Profile/>}</main></div><nav className="bottomNav">{nav.slice(0,5).map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>setPage(n.id)}><n.icon/><span>{n.label==='Overview'?'Home':n.label}</span></button>)}<button onClick={onLogout} className="mobileLogout"><LogOut/></button></nav></div>}

export default function App(){const [auth,setAuth]=useState<AuthMode|null>(null);const [loggedIn,setLoggedIn]=useState(false);if(loggedIn)return <Platform onLogout={()=>setLoggedIn(false)}/>;if(auth)return <Auth mode={auth} onClose={()=>setAuth(null)} onSuccess={()=>setLoggedIn(true)}/>;return <Landing onAuth={setAuth}/>}
